;;; Compiled snippets and support files for `latex-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'latex-mode
		     '(("verb" "\\begin{verbatim}\n$0\n\n\\end{verbatim}\n" "verb" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/verb" nil nil)
		       ("pkg" "\\usepackage{$0}" "usepackage" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/usepackage" nil nil)
		       ("susetup" "\\documentclass[a4paper]{article}\n\\usepackage{su17}\n\\header{%\n  assignment={$1},%\n  authors={${2:authors$(yas-choose-value '(\"Mads Obitsø <\\\\\\texttt{scr411@alumni.ku.dk}>\" \"Mads Obitsø, Jonas Klausen, Nicolai Rathjen\"))}},%\n  shortAuthors={\\\\texttt{${3:shortAuthors$(yas-choose-value '(\"Obitsø\" \"Obitsø, Klausen, Rathjen\"))}}},%\n  date={$4}\n}\n\n\\begin{document}\n\\maketitle\n$0\n\n\n\\end{document}" "softwareudvikling report setup" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/susetup" nil nil)
		       ("subsub" "\\subsubsection*{${1:name}}\n\n$0" "subsubsection" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/subsubsection" nil nil)
		       ("sub" "\\subsection*{${1:name}}\n$0" "subsection" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/subsection" nil nil)
		       ("subs" "\\subsection{${1:name}}\n\\label{subsec:${1:$(replace-regexp-in-string (regexp-quote \" \")  \"_\" (downcase yas/text) nil 'literal)}}\n$0\n" "subsection with label" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/subs" nil nil)
		       ("setuppy" "% Setup python highlighting\n\\definecolor{deepblue}{rgb}{0,0,0.5}\n\\definecolor{deepred}{rgb}{0.6,0,0}\n\\definecolor{deepgreen}{rgb}{0,0.5,0}\n\n\n% Python style for highlighting\n\\newcommand\\pythonstyle{\\lstset{\n    language=Python,\n    basicstyle=\\ttm,\n    otherkeywords={self},             % Add keywords here\n    keywordstyle=\\ttb\\color{deepblue},\n    emph={MyClass,__init__},          % Custom highlighting\n    emphstyle=\\ttb\\color{deepred},    % Custom highlighting style\n    stringstyle=\\color{deepgreen},\n    frame=tb,                         % Any extra options here\n    showstringspaces=false            % \n  }}\n\n\n% Python environment\n\\lstnewenvironment{python}[1][]\n{\n  \\pythonstyle\n  \\lstset{#1}\n}\n{}\n\n% Python for external files\n\\newcommand\\pythonexternal[2][]{{\n    \\pythonstyle\n    \\lstinputlisting[#1]{#2}}}\n\n% Python for inline\n\\newcommand\\pythoninline[1]{{\\pythonstyle\\lstinline!#1!}}\n" "setuppython" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/setuppython" nil nil)
		       ("setupf" "% Setup F#\n\\definecolor{bluekeywords}{rgb}{0.13,0.13,1}\n\\definecolor{greencomments}{rgb}{0,0.5,0}\n\\definecolor{turqusnumbers}{rgb}{0.17,0.57,0.69}\n\\definecolor{redstrings}{rgb}{0.5,0,0}\n\\lstdefinelanguage{FSharp}\n                {morekeywords={let, new, match, with, rec, open, module, namespace, type, of, member, and, for, in, do, begin, end, fun, function, try, mutable, if, then, else},\n    keywordstyle=\\color{bluekeywords},\n    sensitive=false,\n    morecomment=[l][\\color{greencomments}]{///},\n    morecomment=[l][\\color{greencomments}]{//},\n    morecomment=[s][\\color{greencomments}]{{(*}{*)}},\n    morestring=[b]\",\n    stringstyle=\\color{redstrings}\n    }\n" "setupfsharp" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/setupfsharp" nil nil)
		       ("sec" "\\section*{${1:name}}\n$0" "section" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/section" nil nil)
		       ("secs" "\\section{${1:name}}\n\\label{sec:${1:$(replace-regexp-in-string (regexp-quote \" \")  \"_\" (downcase yas/text) nil 'literal)}}\n$0\n" "secs" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/secs" nil nil)
		       ("py" "\\lstset{language=python}\n\\begin[language=python]{lstlisting}\n$0\n\\end{lstlisting}" "python" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/python" nil nil)
		       ("lst" "\\begin{lstlisting}[mathescape]\n$0\n\\end{lstlisting}" "lstlisting" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/lstlisting" nil nil)
		       ("lab" "\\label{$0}" "label" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/label" nil nil)
		       ("item" "\\begin{itemize}\n  \\item $0\n\\end{itemize}" "item" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/itemize" nil nil)
		       ("idsetup" "\\documentclass[a4paper]{article}\n\\usepackage{id17}\n\\header{%\n  assignment={$1},%\n  authors={${2:authors$(yas-choose-value '(\"Mads Obitsø <\\\\\\texttt{scr411@alumni.ku.dk}>\" \"Mads Obitsø, Jonas Klausen, Nicolai Rathjen\"))}},%\n  shortAuthors={\\\\texttt{${3:shortAuthors$(yas-choose-value '(\"Obitsø\" \"Obitsø, Klausen, Rathjen\"))}}},%\n  date={$4}\n}\n\n\\begin{document}\n\\maketitle\n$0\n\n\n\\end{document}" "interaktionsdesign report setup" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/idsetup" nil nil)
		       ("frac" "\\frac{${1:numerator}}{${2:denominator}}$0" "frac" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/frac" nil nil)
		       ("fig" "\\begin{figure}[ht]\n  \\centering\n  \\includegraphics[${1:options}]{figures/${2:path.pdf}}\n  \\caption{$3}\n  \\label{fig:${4:label}}\n\\end{figure}\n\n$0" "figure" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/figure" nil nil)
		       ("enum" "\\begin{enumerate}\n  \\item $0\n\\end{enumerate}" "enumerate" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/enum" nil nil)
		       ("e" "\\emph{$1}$0" "emph" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/emph" nil nil)
		       ("com" "\\textit{\\color{red} Mads:${1:Comment}}$0\n" "comment" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/com" nil nil)
		       ("class" "Class.${1:classname}(\"$1\")\n    ($2)\n    ($3);\n$0\n" "class" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/class" nil nil)
		       ("begin" "\\begin{${1:environment$(yas-choose-value '(\"equation\" \"split\" \"align\" \"figure\" \"enumerate\" \"itemize\" \"\"))${2:*$(yas-choose-value '(\"*\" \"\"))}}}\n$0\n\\end{$1$2}" "begin" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/begin" nil nil)
		       ("basicsetup" "\\documentclass[12pt, a4paper]{article}\n\\usepackage[utf8]{inputenc}\n\\usepackage[danish]{babel}\n\\usepackage [T1]{fontenc}\n\\usepackage[margin=2.5cm]{geometry}\n\\usepackage{hyperref}\n\\usepackage{graphicx}\n\\graphicspath{{figures/}}\n\\usepackage{listings}\n\\usepackage{color}\n\\usepackage{amsfonts, amsmath, amssymb}\n% Enable integration between METAPOST pictures and LaTeX\n% See also: https://www.ctan.org/pkg/gmp\n% and     : http://ctan.mackichan.com/macros/latex2e/contrib/gmp/gmp.pdf\n\\usepackage[shellescape, latex]{gmp}\n\n\n\\title{$1}\n\\author{Mads Obitsø}\n\n\\begin{document}\n\\maketitle \n$0\n\n\\end{document}" "basicsetup" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/basicsetup" nil nil)
		       ("mat5" "\\left[\n\\begin{array}{rrrrr}\n$1 & $2 & $3 & $4 & $5 \\\\\\\n$6 & $7 & $8 & $9 & $10 \\\\\\\n$11 & $12 & $13 & $14 & $15 \\\\\\\n$16 & $17 & $18 & $19 & $20 \\\\\\\n$21 & $22 & $23 & $24 & $25\n\\end{array}\n\\right]\n$0" "5x5matrix" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/5x5mat" nil nil)
		       ("mat3" "\\left[\n\\begin{array}{rrr}\n$1 & $2 & $3 \\\\\\\n$4 & $5 & $6 \\\\\\\n$7 & $8 & $9\n\\end{array}\n\\right]\n$0" "3x3matrix" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/3x3matrix" nil nil)
		       ("mat2" "\\left[\n\\begin{array}{rr}\n$1 & $2  \\\\\\\n$3 & $4\n\\end{array}\n\\right]\n$0" "2x2matrix" nil nil nil "/Users/Mads/.emacs.d/snippets/latex-mode/2x2matrix" nil nil)))


;;; Do not edit! File generated at Tue Jun  6 03:22:16 2017
